kibot:
  version: 1

preflight:
  drc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV
  erc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV

globals:
  field_lcsc_part: LCSC

import:
  - file: JLCPCB
    definitions:
      _KIBOT_PLOT_FOOTPRINT_VALUES: true
  - file: PCB2Blender_2_1

outputs:
  - name: basic_ibom
    comment: Interactive HTML BoM
    type: ibom
    dir: Assembly
    options:
      # https://kibot.readthedocs.io/en/master/configuration/outputs/IBoMOptions.html
      output: "index.%x"
      extra_data_file: "%F.kicad_pcb"
      extra_fields: Description,LCSC
      dark_mode: true
      highlight_pin1: selected
      no_compression: true
      include_nets: true
      include_tracks: true

  - name: basic_diff_pcb
    comment: PCB diff between the last two changes
    type: diff
    dir: diff
    layers:
      - layer: F.Cu
        suffix: F_Cu
        description: Front copper
      - layer: F.Mask
        suffix: F_Mask
        description: Front soldermask (negative)
      - layer: B.Cu
        suffix: B_Cu
        description: Bottom copper
      - layer: B.Mask
        suffix: B_Mask
        description: Bottom soldermask (negative)
      - layer: F.Silkscreen
        suffix: F_Silkscreen
        description: Front silkscreen (artwork)
      - layer: F.Paste
        suffix: F_Paste
        description: Front solder paste
      - layer: User.Comments
        suffix: User_Comments
        description: User comments
      - layer: Edge.Cuts
        suffix: Edge_Cuts
        description: Board shape
      - layer: F.Courtyard
        suffix: F_Courtyard
        description: Front courtyard area
      - layer: F.Fab
        suffix: F_Fab
        description: Front documentation
    options:
      old: KIBOT_LAST-1
      old_type: git
      new: HEAD
      new_type: git
      add_link_id: true

  - name: basic_diff_sch
    comment: Schematic diff between the last two changes
    type: diff
    dir: diff
    options:
      old: KIBOT_LAST-1
      old_type: git
      new: HEAD
      new_type: git
      add_link_id: true
      pcb: false

  - name: renderer_for_present
    comment: Renderer for the presentation
    type: pcbdraw
    dir: Render_for_presentation
    run_by_default: true

  - name: basic_blender_export
    comment: 3D view from top/30 deg/bottom (Blender)
    type: blender_export
    dir: 3D
    options:
      pcb3d: _PCB2Blender_2_1
      outputs:
        - type: render
        - type: blender
      point_of_view:
        - view: top
        - rotate_x: 30
          rotate_z: -20
          file_id: _30deg
        - view: bottom
