name: kibot

on:
    push:
        paths:
            - ".github/workflows/kibot.yaml"
            - "**.kicad_pcb"
            - "**.kicad_sch"
            - "kicad/config.kibot.yaml"

    pull_request:
        paths:
            - "**.kicad_sch"
            - "**.kicad_pcb"

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    kibot:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - uses: INTI-CMNB/KiBot@v2_k9
              with:
                  cache3D: YES
                  # Required - kibot config file
                  config: kicad/config.kibot.yaml
                  # optional - prefix to output defined in config
                  dir: output
                  schema: "kicad/closed-drybox.kicad_sch"
                  # optional - PCB design file
                  board: "kicad/closed-drybox.kicad_pcb"
            - name: upload results
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                  name: output
                  path: output

            - name: Upload artifact (GitHub pages)
              uses: actions/upload-pages-artifact@v4
              with:
                  path: output/Assembly

    # Deployment job
    deploy:
        if: github.ref == 'refs/heads/main'
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: kibot
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4

    # Release job
    release:
        if: github.ref_type == 'tag'
        runs-on: ubuntu-latest
        needs: kibot
        steps:
            - name: Check out repository
              uses: actions/checkout@v5

            - name: Download output artifact
              uses: actions/download-artifact@v5
              with:
                  name: output
                  path: output

            - name: Compress JLCPCB files
              run: zip -r jlcpcb.zip output/JLCPCB

            - name: Release
              uses: softprops/action-gh-release@v2
              if: github.ref_type == 'tag'
              with:
                  files: |
                      output/Assembly/index.html
                      jlcpcb.zip
